//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAGAS.Entidad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BONILLA\\SQLSERVER2008R2;Initial Catalog=SAGAS;User ID=sa;Password=pa$" +
            "$w0rd")]
        public string SAGASConnectionString {
            get {
                return ((string)(this["SAGASConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BONILLA\\SQLSERVER2008R2;Initial Catalog=SAGAS;Persist Security Info=T" +
            "rue;User ID=sa;Password=pa$$w0rd")]
        public string SAGASConnectionString1 {
            get {
                return ((string)(this["SAGASConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-SERVER\\SQLEXPRESS2008R2;Initial Catalog=SAGAS;User ID=sa;Password" +
            "=pa$$w0rd")]
        public string SAGASConnectionString2 {
            get {
                return ((string)(this["SAGASConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.206.2\\SQLEXPRESS2008R2;Initial Catalog=SAGAS;Persist Security" +
            " Info=True;User ID=sa;Password=pa$$w0rd")]
        public string SAGASConnectionString3 {
            get {
                return ((string)(this["SAGASConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=165.98.186.14\\SQLEXPRESS2008R2;Initial Catalog=SAGAS;Persist Security" +
            " Info=True;User ID=sa;Password=pa$$w0rd")]
        public string SAGASConnectionString4 {
            get {
                return ((string)(this["SAGASConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=165.98.186.14\\SQLEXPRESS2008R2;Initial Catalog=SAGAS;User ID=sa;Passw" +
            "ord=pa$$w0rd")]
        public string SAGASConnectionString5 {
            get {
                return ((string)(this["SAGASConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-SERVER\\SQLEXPRESS2008R2;Initial Catalog=SAGASDevelopment;User ID=" +
            "sa;Password=pa$$w0rd")]
        public string SAGASDevelopmentConnectionString {
            get {
                return ((string)(this["SAGASDevelopmentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=161.0.36.74\\SQLEXPRESS2008R2;Initial Catalog=SAGAS;User ID=sa;Passwor" +
            "d=pa$$w0rd")]
        public string SAGASConnectionString6 {
            get {
                return ((string)(this["SAGASConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BONILLAL\\SQLSERVER2008R2;Initial Catalog=SAGAS;User ID=sa;Password=pa" +
            "$$w0rd")]
        public string SAGASConnectionString7 {
            get {
                return ((string)(this["SAGASConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BONILLAL\\SQLSERVER2008R2;Initial Catalog=SAGAS;User ID=sa")]
        public string SAGASConnectionString8 {
            get {
                return ((string)(this["SAGASConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BONILLAL\\SQLSERVER2008R2;Initial Catalog=SAGASDevelopment;User ID=sa;" +
            "Password=pa$$w0rd")]
        public string SAGASDevelopmentConnectionString1 {
            get {
                return ((string)(this["SAGASDevelopmentConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=161.0.36.74;Initial Catalog=SAGAS;User ID=sa;Password=pa$$w0rd")]
        public string SAGASConnectionString9 {
            get {
                return ((string)(this["SAGASConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BONILLAL\\SQLSERVER2014;Initial Catalog=SAGAS;User ID=sa;Password=pa$$" +
            "w0rd")]
        public string SAGASConnectionString10 {
            get {
                return ((string)(this["SAGASConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SAFIEROPC;Initial Catalog=SAGAS;User ID=sa;Password=pa$$w0rd")]
        public string SAGASConnectionString11 {
            get {
                return ((string)(this["SAGASConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESARROLLOBL-PC;Initial Catalog=SAGAS;User ID=sa;Password=2303")]
        public string SAGASConnectionString12 {
            get {
                return ((string)(this["SAGASConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SAGAS;Initial Catalog=\"SAGAS Dev\";User ID=sa;Password=pa$$w0rd")]
        public string SAGAS_DevConnectionString {
            get {
                return ((string)(this["SAGAS_DevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.206.2;Initial Catalog=\"SAGAS Dev\";User ID=sa;Password=pa$$w0r" +
            "d")]
        public string SAGAS_DevConnectionString1 {
            get {
                return ((string)(this["SAGAS_DevConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.206.2;Initial Catalog=SAGAS;User ID=sa;Password=pa$$w0rd")]
        public string SAGASConnectionString13 {
            get {
                return ((string)(this["SAGASConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SAFIEROPC;Initial Catalog=SAGAS;Persist Security Info=True;User ID=sa" +
            ";Password=pa$$w0rd")]
        public string SAGASConnectionString14 {
            get {
                return ((string)(this["SAGASConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.206.2;Initial Catalog=\"SAGAS Dev\";User ID=sa;Password=pa$$w0r" +
            "d;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string SAGAS_DevConnectionString2 {
            get {
                return ((string)(this["SAGAS_DevConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.206.2;Initial Catalog=\"SAGAS6 Dev\";User ID=sa;Password=pa$$w0" +
            "rd;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string SAGAS6_DevConnectionString {
            get {
                return ((string)(this["SAGAS6_DevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.206.2;Initial Catalog=\"SAGAS6 Dev\";User ID=sa;Password=pa$$w0" +
            "rd")]
        public string SAGAS6_DevConnectionString1 {
            get {
                return ((string)(this["SAGAS6_DevConnectionString1"]));
            }
        }
    }
}
