//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAGAS.Parametros.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAGAS.Parametros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add24 {
            get {
                object obj = ResourceManager.GetObject("add24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anular24 {
            get {
                object obj = ResourceManager.GetObject("Anular24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bulb20 {
            get {
                object obj = ResourceManager.GetObject("bulb20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancel20 {
            get {
                object obj = ResourceManager.GetObject("cancel20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap errorTitle {
            get {
                object obj = ResourceManager.GetObject("errorTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Excel24 {
            get {
                object obj = ResourceManager.GetObject("Excel24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exportar24 {
            get {
                object obj = ResourceManager.GetObject("exportar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filterDelete24 {
            get {
                object obj = ResourceManager.GetObject("filterDelete24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google_keep {
            get {
                object obj = ResourceManager.GetObject("google_keep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap informationIcon {
            get {
                object obj = ResourceManager.GetObject("informationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap infoTitle {
            get {
                object obj = ResourceManager.GetObject("infoTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap key_add {
            get {
                object obj = ResourceManager.GetObject("key_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap key_go {
            get {
                object obj = ResourceManager.GetObject("key_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap modificar24 {
            get {
                object obj = ResourceManager.GetObject("modificar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mostrar {
            get {
                object obj = ResourceManager.GetObject("Mostrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen Arqueo de Islas Abiertas o Islas sin Arqueo, verifique los arqueos de este turno para finalizar este proceso..
        /// </summary>
        public static string MSGARQUEOSISLASABIERTOS {
            get {
                return ResourceManager.GetString("MSGARQUEOSISLASABIERTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los cambios se han guardado correctamente..
        /// </summary>
        public static string MSGCAMBIOSGUARDADOS {
            get {
                return ResourceManager.GetString("MSGCAMBIOSGUARDADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Periodo Contable para esta fecha ya esta cerrado.
        /// </summary>
        public static string MSGCIERRECONTABLE {
            get {
                return ResourceManager.GetString("MSGCIERRECONTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El compronte contable del movimiento esta descuadrado..
        /// </summary>
        public static string MSGCOMPROBANTEDESCUADRADO {
            get {
                return ResourceManager.GetString("MSGCOMPROBANTEDESCUADRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido una interrupción en el proceso del sistema..
        /// </summary>
        public static string MSGERROR {
            get {
                return ResourceManager.GetString("MSGERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El total del movimiento es 0 &quot;CERO&quot;, ¿Desea Continuar?.
        /// </summary>
        public static string MSGESCERO {
            get {
                return ResourceManager.GetString("MSGESCERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se esta pagando un documento con fecha mayor a la fecha de pago..
        /// </summary>
        public static string MSGFECHADOCUMENTOMAYORFECHAPAGO {
            get {
                return ResourceManager.GetString("MSGFECHADOCUMENTOMAYORFECHAPAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los movimientos de inventario esta bloqueado para esta fecha.  .
        /// </summary>
        public static string MSGINVENTARIOBLOQUEADO {
            get {
                return ResourceManager.GetString("MSGINVENTARIOBLOQUEADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licencia del sistema es invalida..
        /// </summary>
        public static string MSGLICENCIAINVALIDA {
            get {
                return ResourceManager.GetString("MSGLICENCIAINVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue modificado. ¿Desea guardar el registro antes de cerrar la ventana?.
        /// </summary>
        public static string MSGMODIFICADOCLOSING {
            get {
                return ResourceManager.GetString("MSGMODIFICADOCLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue modificado. ¿Desea guardar el registro antes de finalizar?.
        /// </summary>
        public static string MSGMODIFICADOFINALIZAR {
            get {
                return ResourceManager.GetString("MSGMODIFICADOFINALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue modificado. ¿Desea guardar el registro antes de generar la vista previa?.
        /// </summary>
        public static string MSGMODIFICADOVISTAPREVIA {
            get {
                return ResourceManager.GetString("MSGMODIFICADOVISTAPREVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Estación seleccionada no tiene asignado un Administrador..
        /// </summary>
        public static string MSGNOADMNISTRADOR {
            get {
                return ResourceManager.GetString("MSGNOADMNISTRADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Estación seleccionada no tiene asignado un Contador..
        /// </summary>
        public static string MSGNOCONTADOR {
            get {
                return ResourceManager.GetString("MSGNOCONTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede Inactivar este registro. Esta siendo utilizado por el sistema..
        /// </summary>
        public static string MSGNOPUEDEINACTIVAR {
            get {
                return ResourceManager.GetString("MSGNOPUEDEINACTIVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe Tipo de Cambio para la fecha seleccionada, favor comunicarse con oficina central..
        /// </summary>
        public static string MSGNOTIPOCAMBIO {
            get {
                return ResourceManager.GetString("MSGNOTIPOCAMBIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea crear un nuevo registro?.
        /// </summary>
        public static string MSGNUEVOREGISTRO {
            get {
                return ResourceManager.GetString("MSGNUEVOREGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor revise los datos requeridos de la ventana..
        /// </summary>
        public static string MSGREVISARDATOS {
            get {
                return ResourceManager.GetString("MSGREVISARDATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar la Cuenta Contable..
        /// </summary>
        public static string MSGSELECCIONARCC {
            get {
                return ResourceManager.GetString("MSGSELECCIONARCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede inactivar, el registro actual es el último..
        /// </summary>
        public static string MSGULTIMOREGISTROINACTIVO {
            get {
                return ResourceManager.GetString("MSGULTIMOREGISTROINACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha Inicial no debe ser igual o mayor que la Fecha Final..
        /// </summary>
        public static string MSGVALIDARFECHA {
            get {
                return ResourceManager.GetString("MSGVALIDARFECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Validar la Licencia del Sistema?.
        /// </summary>
        public static string MSGVALIDARLICENCIA {
            get {
                return ResourceManager.GetString("MSGVALIDARLICENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ya esta anulado..
        /// </summary>
        public static string MSGYAANULADO {
            get {
                return ResourceManager.GetString("MSGYAANULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap No20 {
            get {
                object obj = ResourceManager.GetObject("No20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ocultar {
            get {
                object obj = ResourceManager.GetObject("Ocultar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ok20 {
            get {
                object obj = ResourceManager.GetObject("Ok20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_key_icon {
            get {
                object obj = ResourceManager.GetObject("open_key_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe de finalizar la operacion con el signo &apos;)&apos; y el operador matemático de división  &apos;/&apos; o multiplicación &apos;*&apos;..
        /// </summary>
        public static string OPERACIONMATEMATICAARQUEO {
            get {
                return ResourceManager.GetString("OPERACIONMATEMATICAARQUEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PDF24 {
            get {
                object obj = ResourceManager.GetObject("PDF24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap print24 {
            get {
                object obj = ResourceManager.GetObject("print24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap printerLocal {
            get {
                object obj = ResourceManager.GetObject("printerLocal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap questionTitle {
            get {
                object obj = ResourceManager.GetObject("questionTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh24 {
            get {
                object obj = ResourceManager.GetObject("refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reportes {
            get {
                object obj = ResourceManager.GetObject("Reportes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reports {
            get {
                object obj = ResourceManager.GetObject("Reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reports_icon {
            get {
                object obj = ResourceManager.GetObject("Reports_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SAGAS_logo_final_01 {
            get {
                object obj = ResourceManager.GetObject("SAGAS logo final-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SagasLogo {
            get {
                object obj = ResourceManager.GetObject("SagasLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SAGASLogo48 {
            get {
                object obj = ResourceManager.GetObject("SAGASLogo48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Salir24 {
            get {
                object obj = ResourceManager.GetObject("Salir24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_key_icon {
            get {
                object obj = ResourceManager.GetObject("save_key_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveDB24 {
            get {
                object obj = ResourceManager.GetObject("SaveDB24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de activar el registro?.
        /// </summary>
        public static string SEGUROACTIVAR {
            get {
                return ResourceManager.GetString("SEGUROACTIVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de anular el registro?.
        /// </summary>
        public static string SEGUROANULAR {
            get {
                return ResourceManager.GetString("SEGUROANULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de aperturar el día?.
        /// </summary>
        public static string SEGUROAPERTURARDIA {
            get {
                return ResourceManager.GetString("SEGUROAPERTURARDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de borrar el registro?.
        /// </summary>
        public static string SEGUROBORRAR {
            get {
                return ResourceManager.GetString("SEGUROBORRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de inactivar el registro?.
        /// </summary>
        public static string SEGUROINACTIVAR {
            get {
                return ResourceManager.GetString("SEGUROINACTIVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TestDB24 {
            get {
                object obj = ResourceManager.GetObject("TestDB24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando cálculos de los Registros.
        /// </summary>
        public static string TXTACTUALIZANDO {
            get {
                return ResourceManager.GetString("TXTACTUALIZANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulando el registro.
        /// </summary>
        public static string TXTANULANDO {
            get {
                return ResourceManager.GetString("TXTANULANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando los Datos del Registro.
        /// </summary>
        public static string TXTCARGANDO {
            get {
                return ResourceManager.GetString("TXTCARGANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrando e Imprimiendo Registro.
        /// </summary>
        public static string TXTCIERREREGISTRO {
            get {
                return ResourceManager.GetString("TXTCIERREREGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando el formulario.
        /// </summary>
        public static string TXTFORMULARIO {
            get {
                return ResourceManager.GetString("TXTFORMULARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando los Registros.
        /// </summary>
        public static string TXTGUARDANDO {
            get {
                return ResourceManager.GetString("TXTGUARDANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando Vista Previa.
        /// </summary>
        public static string TXTVISTAPREVIA {
            get {
                return ResourceManager.GetString("TXTVISTAPREVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warningTitle {
            get {
                object obj = ResourceManager.GetObject("warningTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zanzibar {
            get {
                object obj = ResourceManager.GetObject("Zanzibar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
